
-- Seed 50 Realistic Fake Writers for Passing Lines Feed
-- Run this to populate the discovery feed with diverse, interesting creators.

INSERT INTO public.profiles (id, name, handle, bio, avatar_url, user_intent, onboarding_completed, writing_preferences)
VALUES
  (gen_random_uuid(), 'Elena Vance', 'elena_v', 'Micro-fiction about forgotten places. Collecting shadows.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Elena', 'writer', true, ARRAY['Short stories', 'Flash fiction']),
  (gen_random_uuid(), 'Marcus Thorne', 'thorne_noir', 'Serialized detective stories set in a rain-soaked future.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Marcus', 'writer', true, ARRAY['Serialized stories']),
  (gen_random_uuid(), 'Junko T.', 'junko_zines', 'Scissors, glue, and photocopied dreams. Dada forever.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Junko', 'writer', true, ARRAY['Zines', 'Experimental']),
  (gen_random_uuid(), 'Silas Marner', 'weaver_silas', 'Threads of thought woven into essays on modern stoicism.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Silas', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Amara Singh', 'amara_poetry', 'Haikus for the digital age. Nature reclaiming the server room.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Amara', 'writer', true, ARRAY['Poetry']),
  (gen_random_uuid(), 'The Midnight Baker', 'midnight_yeast', 'Recipes and ruminations from the graveyard shift.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Midnight', 'writer', true, ARRAY['Essays', 'Experimental']),
  (gen_random_uuid(), '0xGhost', 'zero_ghost', 'Transmissions from the machine. Glitch art and code poetry.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Ghost', 'writer', true, ARRAY['Experimental', 'Poetry']),
  (gen_random_uuid(), 'Clara Oswald', 'impossible_girl', 'Travel journals from places that dont exist yet.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Clara', 'writer', true, ARRAY['Short stories']),
  (gen_random_uuid(), 'Dr. Aris', 'aris_notes', 'Field notes on urban botany and concrete ecosystems.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Aris', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Lila & The Cats', 'lila_cats', 'Conversations with my feline overlords. Illustrated.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Lila', 'writer', true, ARRAY['Zines', 'Short stories']),
  (gen_random_uuid(), 'Kaelen R.', 'kaelen_writes', 'Epic fantasy snippets. Building a world one page at a time.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Kaelen', 'writer', true, ARRAY['Fiction']),
  (gen_random_uuid(), 'Sasha Greyv', 'sasha_greyv', 'Architectural critiques of invisible cities.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Sasha', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Benny Beats', 'benny_b', 'Lyrics without music. Rhythm on paper.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Benny', 'writer', true, ARRAY['Poetry']),
  (gen_random_uuid(), 'Maya Angelou (Spirit)', 'maya_spirit', 'Paying homage to the greats through distinct new voices.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Maya', 'writer', true, ARRAY['Poetry']),
  (gen_random_uuid(), 'Retro Futurist', 'retro_future', 'News from 1985s version of 2025.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Retro', 'writer', true, ARRAY['Fiction', 'Zines']),
  (gen_random_uuid(), 'Garden of Words', 'word_garden', 'Planting seeds of vocabulary. Etymology nerdery.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Garden', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Lucas Ink', 'lucas_ink', 'Hand-drawn typography and calligraphy layouts.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Lucas', 'writer', true, ARRAY['Zines']),
  (gen_random_uuid(), 'Sarah J.', 'sarah_frights', 'Horror shorts. Don''t read with the lights off.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Sarah', 'writer', true, ARRAY['Fiction']),
  (gen_random_uuid(), 'Zenith', 'zenith_peak', 'Mountain climbing logs and high-altitude philosophy.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Zenith', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Echo', 'echo_loc', 'Repeated patterns. Mantras. Meditations.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Echo', 'writer', true, ARRAY['Experimental']),
  (gen_random_uuid(), 'Oliver Twist', 'oliver_t', 'Dickensian satire for the gig economy.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Oliver', 'writer', true, ARRAY['Fiction']),
  (gen_random_uuid(), 'Nadia Cooks', 'nadia_cooks', 'Family recipes and the stories behind the stains.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Nadia', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'The Observer', 'observer_eye', 'People watching at Grand Central. A daily log.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Observer', 'writer', true, ARRAY['Non-fiction']),
  (gen_random_uuid(), 'Pixel Pete', 'pixel_pete', 'Reviewing video games that don''t exist.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Pete', 'writer', true, ARRAY['Fiction', 'Reviews']),
  (gen_random_uuid(), 'Hana Song', 'hana_songs', 'Lyric essays on pop culture and heartbreak.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Hana', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Dante', 'dante_inferno', 'Navigating the nine circles of corporate middle management.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Dante', 'writer', true, ARRAY['Satire', 'Fiction']),
  (gen_random_uuid(), 'Luna Love', 'luna_phases', 'Astrology charts and moon poetry.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Luna', 'writer', true, ARRAY['Poetry']),
  (gen_random_uuid(), 'Techno Pagan', 'techno_pagan', 'Rituals for the hard drive. Blessing the GPU.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Techno', 'writer', true, ARRAY['Experimental']),
  (gen_random_uuid(), 'Jasper F.', 'jasper_f', 'Letters to people I''ll never send.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Jasper', 'writer', true, ARRAY['Letters', 'Non-fiction']),
  (gen_random_uuid(), 'Ruby Red', 'ruby_tuesday', 'Reviews of red lipsticks and red wines.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Ruby', 'writer', true, ARRAY['Reviews']),
  (gen_random_uuid(), 'Max Power', 'max_power_clean', 'Sustainable living tips. Zero waste journals.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Max', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Sophie World', 'sophie_phil', 'Philosophy 101 simplified. Big ideas, small words.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Sophie', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Gonzo', 'gonzo_journo', 'Erratic reporting from the edge of sanity.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Gonzo', 'writer', true, ARRAY['Journalism']),
  (gen_random_uuid(), 'Fable', 'fable_weaver', 'Retelling Grimm''s fairy tales with modern twists.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Fable', 'writer', true, ARRAY['Fiction']),
  (gen_random_uuid(), 'Orion', 'orion_hunter', 'Star maps and constellation myths properly explained.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Orion', 'writer', true, ARRAY['Non-fiction']),
  (gen_random_uuid(), 'Ada Lovelace', 'ada_code', 'The poetry of algorithms. Logic gates and rhyme schemes.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Ada', 'writer', true, ARRAY['Poetry']),
  (gen_random_uuid(), 'B.B. King (Fan)', 'blues_notes', 'History of the blues. One track at a time.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Blues', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Catcher', 'rye_catcher', 'Teen angst, bottled and aged. Salinger vibes.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Catcher', 'writer', true, ARRAY['Fiction']),
  (gen_random_uuid(), 'Velvet', 'velvet_under', 'Underground music scene reports from 1969.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Velvet', 'writer', true, ARRAY['Zines']),
  (gen_random_uuid(), 'Flux', 'flux_cap', 'Time travel paradoxes discussed in detail.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Flux', 'writer', true, ARRAY['Sci-Fi']),
  (gen_random_uuid(), 'Nomad', 'digital_nomad', 'WiFi passwords and coffee shops around the world.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Nomad', 'writer', true, ARRAY['Travel']),
  (gen_random_uuid(), 'Rust', 'rust_belt', 'Stories from the factory floor. Industrial decay.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Rust', 'writer', true, ARRAY['Non-fiction']),
  (gen_random_uuid(), 'Neon', 'neon_nights', 'Cyberpunk vignettes. High tech, low life.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Neon', 'writer', true, ARRAY['Sci-Fi']),
  (gen_random_uuid(), 'Paper Plane', 'paper_av', 'Instructions on folding things. Origami and more.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Paper', 'writer', true, ARRAY['How-to']),
  (gen_random_uuid(), 'Inkwell', 'ink_stained', 'Calligraphy practice sheets and tips.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Inkwell', 'writer', true, ARRAY['Art']),
  (gen_random_uuid(), 'Lens', 'camera_obscura', 'Photography theory. Seeing light.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Lens', 'writer', true, ARRAY['Essays']),
  (gen_random_uuid(), 'Vinyl', 'vinyl_scratch', ' Liner notes for albums that should exist.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Vinyl', 'writer', true, ARRAY['Music']),
  (gen_random_uuid(), 'Typo', 'typo_king', 'Celebrating the happy accidnets in text.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Typo', 'writer', true, ARRAY['Experimental']),
  (gen_random_uuid(), 'Lorem Ipsum', 'lorem_real', 'Translating filler text into meaning.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Lorem', 'writer', true, ARRAY['Experimental']),
  (gen_random_uuid(), 'Final Boss', 'final_level', 'Game design documents for life.', 'https://api.dicebear.com/7.x/notionists/svg?seed=Final', 'writer', true, ARRAY['Essays'])
ON CONFLICT (handle) DO NOTHING;
